data:
  path:
    train:
      x_path: "./PPG_data/splitted_data/x_train.npy"
      y_path: "./PPG_data/splitted_data/y_train.npy"
    valid:
      x_path: "./PPG_data/splitted_data/x_val.npy"
      y_path: "./PPG_data/splitted_data/y_val.npy"
    test:
      x_path: "./PPG_data/splitted_data/x_test.npy"
      y_path: "./PPG_data/splitted_data/y_test.npy"
  loader:
      batch_size: 1024
      num_workers: 4
      pin_memory: True
      drop_last: False
      persistent_workers: False

model:
  task: binary
  num_classes: 2
  lr: 0.0001
  loss_name: bce
  use_lr_scheduler: True
  lr_warmup_ratio: 0.1
  device: cuda
  config:
    hyperparameters:
      classifier:
        signal_channels: 1
        stride: 1
    metrics:
      accuracy: 1
      cf_matrix: 1
      f1: 1


trainer:
  parameters:
    accelerator: "gpu"
    strategy: "auto"
    devices: "auto"
    num_nodes: 1
    precision: "16"
    fast_dev_run: False
    max_epochs: 30
    min_epochs: 1
    max_steps: -1
    min_steps: Null
    max_time: Null
    limit_train_batches: Null
    limit_val_batches: Null
    limit_test_batches: Null
    limit_predict_batches: null
    overfit_batches: 0.0
    val_check_interval: null
    check_val_every_n_epoch: 1
    num_sanity_val_steps: 0
    log_every_n_steps: 200
    enable_checkpointing: True
    enable_progress_bar: True
    enable_model_summary: null
    accumulate_grad_batches: 1
    gradient_clip_val: null
    gradient_clip_algorithm: null
    deterministic: null
    benchmark: null
    inference_mode: True
    profiler: null
    detect_anomaly: False
    plugins: null
    sync_batchnorm: False
    reload_dataloaders_every_n_epochs: 0
    default_root_dir: null
  callbacks:
    model_checkpoint:
      dirpath: "checkpoints"
      filename: "resnet18-{epoch:02d}-{valid_loss:2f}-{valid_accuracy:2f}"
      monitor: "valid_loss"
      verbose: True
      save_last: True
      save_top_k: 3
      save_weights_only: False
      mode: "min"
      auto_insert_metric_name: True
      every_n_train_steps: Null
      train_time_interval: Null
      every_n_epochs: Null
      save_on_train_epoch_end: False
    logger:
      save_dir: logs/
      name: ""
      version: Null
      log_graph: False
      default_hp_metric: True
      prefix: ""
      sub_dir: Null
    early_stop:
      monitor: "valid_loss"
      min_delta: 0.5
      patience: 10
      verbose: True
      mode: "min"
      strict: True
      check_finite: True
      stopping_threshold: null
      divergence_threshold: null
      check_on_train_epoch_end: False
    progress_bar:
      refresh_rate: 10
      process_position: 0


experiment:
  train: True
  test: False
  resume_ckpt: False
  ckpt_path: null
  saved_model_path: null
