data:
  path:
    train:
      x_path: "/Users/cdllyyy/Desktop/Ectopics_in_PPG/Ectopics_Detection_from_PPG/PPG_data/splitted_data/x_train.npy"
      y_path: "/Users/cdllyyy/Desktop/Ectopics_in_PPG/Ectopics_Detection_from_PPG/PPG_data/splitted_data/y_train.npy"
    valid:
      x_path: "/Users/cdllyyy/Desktop/Ectopics_in_PPG/Ectopics_Detection_from_PPG/PPG_data/splitted_data/x_val.npy"
      y_path: "/Users/cdllyyy/Desktop/Ectopics_in_PPG/Ectopics_Detection_from_PPG/PPG_data/splitted_data/y_val.npy"
    test:
      x_path: "/Users/cdllyyy/Desktop/Ectopics_in_PPG/Ectopics_Detection_from_PPG/PPG_data/splitted_data/x_test.npy"
      y_path: "/Users/cdllyyy/Desktop/Ectopics_in_PPG/Ectopics_Detection_from_PPG/PPG_data/splitted_data/y_test.npy"
  loader:
      batch_size: 1024
      num_workers: 4
      pin_memory: True
      drop_last: False
      persistent_workers: False

model:
  task: binary
  num_classes: 2
  lr: 0.0001
  loss_name: gce
  device: cuda
  hyperparameters:
    classifier:
      in_channels: 1
      stride: 1
  metrics:
    accuarcy: 1
    cf_matrix: 1
    f1: 1


trainer:
  parameters:
  
  logger: